#ifndef UILAYOUT_H
#define UILAYOUT_H

#define DEFAULT_UI_WIDTH  521
#define DEFAULT_UI_HEIGHT 121
#define DEFAULT_UI_LEFT_MARGIN 10
#define DEFAULT_UI_TOP_MARGIN  10
#define DEFAULT_UI_MENU_HEIGHT 19
#define DEFAULT_UI_BAR_HEIGHT  21

#define DEVICE_UI_WIDTH  465
#define DEVICE_UI_HEIGHT 841
#define DEVICE_UI_LEFT_MARGIN 10
#define DEVICE_UI_TOP_MARGIN  10

#define GROUP_BOX_LEFT_MARGIN 9
#define GROUP_BOX_TOP_MARGIN  19
#define GROUP_BOX_WIDTH  441
#define GROUP_BOX_HEIGHT 811

#define ABOUT_DIALOG_WIDTH  350
#define ABOUT_DIALOG_HEIGHT 266
#define ABOUT_DIALOG_LEFT_MARGIN 10
#define ABOUT_DIALOG_TOP_MARGIN  10

#endif
