#ifndef UILAYOUT_H
#define UILAYOUT_H

#define DEFAULT_UI_WIDTH  560
#define DEFAULT_UI_HEIGHT 210
#define DEFAULT_UI_MENU_HEIGHT 21

#define GROUP_BOX_WIDTH   500
#define GROUP_BOX_HEIGHT  850
#define GROUP_BOX_WIDTH_MARGIN  10
#define GROUP_BOX_HEIGHT_MARGIN 10

#endif
